name: Automatic GH release (testing)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get java version
        id: java_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'java_version'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ steps.java_version.outputs.value }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup forge mdk
        run: ./gradlew init

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get minecraft version
        id: mc_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'mc_version'

      - name: GitHub publish release
        uses: softprops/action-gh-release@v1
        with:
          name: MC ${{ steps.mc_version.outputs.value }} build, updated at ${{ github.event.repository.updated_at}}
          tag_name: experimental
          body: |
            ⚠️ This is an automatically generated file with untested content. Be extremely careful not to use this in your main world without creating backups! ⚠️
          files: build/libs/*${{ steps.mc_version.outputs.value }}-*.jar
